### ISSUE TITLE
Can the node editor be split out into its own package?

### ISSUE THREAD

**Issue by masonwheeler** [Jcparkyn/nodexr#117]
Right now, this project is the top Google result for "Blazor node editor."  And it appears to be pretty much the *only* Blazor node editor available... and its design is constrained to the highly specific domain of regex editing.

Would it be possible to separate out the node editor into its own package, and then have the regex editor be one thing implemented on top of that, so that people who want node editors for other purposes will be able to use it without it dragging a bunch of irrelevant regex-editing cruft into their projects?

**Comment by Jcparkyn** [comment]
Definitely possible, but it would be quite a lot of work due to the fact that it wasn't a priority throughout most of the development (although I agree it should have been). I tried doing this a couple of months ago, but the further I got, the more it started to look like [Z.Blazor.Diagrams](https://github.com/Blazor-Diagrams/Blazor.Diagrams) with some custom components and CSS for the nodes themselves. Part of the problem is that there are a lot of different ways to make node editors, so any functionality provided by the library would need to be highly customizable.

My suggestion for now would be to use Z.Blazor.Diagrams (or something similar) in your project, and adapt the relevant view components that you want from Nodexr (assuming you want a similar style) so that they're compatible with that.

That being said, you're welcome to have a go at refactoring the node editor in Nodexr into a separate package if that's something you're interested in. I can share the work I did on it previously, but there would still be a large amount of work needed in order to do it properly.
