### ISSUE TITLE
A Question .

### ISSUE THREAD

**Issue by kiranmaya** [Jcparkyn/nodexr#122]
Hi, I'm writing a Trading application, I need a node-based logic editor, will this work for my needs, does it have a start node and end node, custom node example, etc. 
this is screenshot of winForms.Can I replicate with these nodes just by writing custom nodes ?
![Screenshot_2](https://user-images.githubusercontent.com/3712631/174709795-2ccda481-9ecb-43f0-8f05-50f0deb2e894.jpg)

**Comment by Jcparkyn** [comment]
In theory you could take the code from Nodexr and implement all those features, but it won't be easy since the node editor in Nodexr was never really designed to be used in other projects. I've improved this a bit over time, but there's still a lot of things that would need to be rewritten (e.g., drag/drop and the calculations for the placement of noodles).

I'd suggest using something like [Blazor.Diagrams](https://github.com/Blazor-Diagrams/Blazor.Diagrams) instead, but keep in mind that there will still be quite a lot of work to implement the logic for dataflow etc. between nodes.
